// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('NwTimerApp', []);

  app.controller('MainCtrl', function($scope) {
    var alarmPlaying, alarmSound, endTime, intervalHandle, parseTime, playAlarm, setDisplay, stopAlarm, timerTick, updateTime;
    $scope.clockIsRunning = false;
    endTime = -1;
    intervalHandle = null;
    alarmPlaying = false;
    $scope.timeOnClock = "00:00:00";
    $scope.isOverunning = false;
    alarmSound = new buzz.sound("sounds/alarm", {
      formats: ["ogg", "mp3"]
    });
    parseTime = function() {
      var hours, minutes, parts, seconds;
      parts = $scope.timeOnClock.split(":");
      seconds = parseInt(parts[2]);
      minutes = parseInt(parts[1]);
      hours = parseInt(parts[0]);
      return (hours * 3600 + minutes * 60 + seconds) * 1000;
    };
    setDisplay = function(timeInMs) {
      var hours, minutes, seconds;
      hours = Math.floor(timeInMs / 3600000);
      minutes = Math.floor((timeInMs - (hours * 3600000)) / 60000);
      seconds = Math.floor((timeInMs - (minutes * 60000)) / 1000);
      return $scope.timeOnClock = ("00" + hours).slice(-2) + ":" + ("00" + minutes).slice(-2) + ":" + ("00" + seconds).slice(-2);
    };
    updateTime = function() {
      var timeLeft;
      timeLeft = endTime - new Date().getTime();
      if (timeLeft <= 0) {
        $scope.isOverunning = true;
        timeLeft = Math.abs(timeLeft);
        if (!alarmPlaying) {
          playAlarm();
        }
      } else {
        if (alarmPlaying) {
          stopAlarm();
        }
        $scope.isOverunning = false;
      }
      return setDisplay(timeLeft);
    };
    playAlarm = function() {
      alarmPlaying = true;
      return alarmSound.play().fadeIn().loop();
    };
    stopAlarm = function() {
      alarmPlaying = false;
      return alarmSound.stop();
    };
    timerTick = function() {
      return $scope.$apply(function() {
        return updateTime();
      });
    };
    $scope.start = function() {
      endTime = new Date().getTime() + parseTime();
      $scope.clockIsRunning = true;
      stopAlarm();
      updateTime();
      return intervalHandle = setInterval(timerTick, 500);
    };
    $scope.stop = function() {
      $scope.clockIsRunning = false;
      stopAlarm();
      return clearInterval(intervalHandle);
    };
    $scope.clear = function() {
      $scope.stop();
      $scope.isOverunning = false;
      return $scope.timeOnClock = "00:00:00";
    };
    $scope.addTime = function(secs) {
      var timeLeft;
      timeLeft = parseTime() + secs * 1000;
      console.log(endTime);
      endTime = endTime + secs * 1000;
      console.log(endTime);
      return setDisplay(timeLeft);
    };
    return $scope.addNumber = function(num) {
      var display, ut;
      display = $scope.timeOnClock.replace(/:/g, "");
      ut = display + num;
      $scope.timeOnClock = ut.slice(1, 3) + ":" + ut.slice(3, 5) + ":" + ut.slice(5, 7);
      return console.log($scope.timeOnClock);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
